#!/bin/bash

set -e

. /usr/share/debconf/confmodule

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

# Try to stop a backup in a sane way. If it does not success let the admin
# do it himself. No backup directories should be removed while a backup
# is running!
stop_backup() {
  set +e
  # TODO - attempt to stop backup correctly
  cmd="/usr/bin/facsimile exit"
  $cmd
  errno=$?
  set -e
   
  if [ "$?" != 0 ]; then
    echo "Trying to stop a Facsimile backup resulted in exitcode $?." 1>&2
    echo "Stop it yourself and try again!" 1>&2
    db_stop
    exit 1
  fi
}

stop_backup
