dist: trusty
sudo: required
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
cache:
  directories:
  - $HOME/.ivy2 
before_script:
  - sudo add-apt-repository ppa:zfs-native/stable -y
  - sudo apt-get update
  - sudo apt-get install autopoint jq libfuse-dev libboost-serialization-dev librlog-dev sed
  - sudo apt-get install build-essential linux-headers-`uname -r`
  - mkdir -p /tmp/encfs
  - dir=`pwd`
  - pushd /tmp/encfs
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/e/encfs/encfs_1.8.1.orig.tar.xz
  - tar xf encfs_1.8.1.orig.tar.xz
  - pushd encfs-1.8.1
  - patch -p1 < $dir/encfs_patch
  - autoreconf -if && ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu && make && sudo make install
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
  - popd
  - popd
  - sudo apt-get install ubuntu-zfs mountall openssh-server openssh-client rsync coreutils libc-bin util-linux
  - sudo /sbin/modprobe zfs
  - sudo zpool status
  - fallocate -l 500M /tmp/zfsfile
  - sudo zpool create tank /tmp/zfsfile
  - sudo zfs create tank/backup
  - sudo zfs create tank/backup/eldorado
  - sudo zfs snapshot tank/backup/eldorado@test
  - ls -al /tank/backup/eldorado/.zfs/snapshot/test
  - sudo zfs destroy -r tank/backup
  - sudo zpool destroy tank
  - rm /tmp/zfsfile
  - sudo sh -c "ssh-keygen -t rsa -N '' -f ~root/.ssh/id_rsa"
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - sudo cat ~root/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - sudo sh -c "cat ~root/.ssh/id_rsa.pub >> ~root/.ssh/authorized_keys"
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keygen -R localhost
  - ssh-keyscan localhost >> ~/.ssh/known_hosts
  - sudo touch ~root/.ssh/known_hosts
  - sudo ssh-keygen -R localhost
  - sudo sh -c "ssh-keyscan localhost >> ~root/.ssh/known_hosts"
  - ssh localhost date # keeping this line ensures that a failure in ssh keying will show up as a CI hung build
  - ssh travis@localhost date
  - sudo ssh localhost date
  - sudo ssh travis@localhost date
script:
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success: "sbt coverageReport coveralls"
