#! /usr/bin/python3 -u
# -*- coding: utf-8; -*-
"""
(C) Copyright 2016 Taylor Raack.

Facsimile Toolbar is free software: you can redistribute it and/or modify
it under the terms of the Affero GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Facsimile Toolbar is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
Affero GNU General Public License for more details.

You should have received a copy of the Affero GNU General Public License
along with Facsimile Toolbar.  If not, see <http://www.gnu.org/licenses/>.
"""

from gi.repository import AppIndicator3
from gi.repository import Gtk, GLib, GObject
import collections
import fcntl
import simplejson as json
import os
import stat
import subprocess
import sys
import threading
import time

LocalConfiguration = collections.namedtuple('LocalConfiguration', [])
RemoteConfiguration = collections.namedtuple('RemoteConfiguration', ['host','user','private_key_saved','path'])
Configuration = collections.namedtuple('Configuration', ['automaticBackups', 'remoteConfiguration', 'localConfiguration', 'configurationType'])

class ConfigurationDialog():
    def __init__(self, save_configuration_callback):
        self.reset_on_show = True
        self.save_configuration_callback = save_configuration_callback
        self.gladefile = "/usr/share/facsimile-toolbar/facsimile-configuration.glade"
        self.builder = Gtk.Builder()
        self.builder.add_from_file(self.gladefile)

        self.builder.connect_signals(self)
    
        self.window = self.builder.get_object("configuration")
        self.backup_type = self.builder.get_object("backup_type")
        self.local_box = self.builder.get_object("local_box")
        self.remote_box = self.builder.get_object("remote_box")
        
        self.automatic_backups = self.builder.get_object("automatic_backups")
        self.remote_host = self.builder.get_object("remote_host")
        self.user = self.builder.get_object("user")
        self.private_key = self.builder.get_object("private_key")
        self.path = self.builder.get_object("path")
        
        self.private_key_contents = None

    def show(self, configuration):
        self.automatic_backups.set_active(configuration.get("automaticBackups", False))

        remote_configuration = configuration.get("remoteConfiguration", {})
        self.remote_host.set_text(remote_configuration.get("host", ""))
        self.user.set_text(remote_configuration.get("user", ""))
        self.private_key.set_text("<saved>" if remote_configuration.get("private_key_saved", False) else "")
        self.path.set_text(remote_configuration.get("path", ""))

        local_configuration = configuration.get("localConfiguration", {})

        self.backup_type.set_active([row[0] for row in self.backup_type.get_model()].index(configuration.get("configurationType").title()))

        self.window.present()
    
    def on_private_key_chooser_file_set(self, file_set):
        me = "hi"
        # read private key contents into memory
        #self.private_key_contents = 
        
    def on_apply_clicked(self, item):
        if not self.save_configuration_callback(Configuration(
                               localConfiguration = LocalConfiguration(),
                               remoteConfiguration = RemoteConfiguration(
                                  host = self.remote_host.get_text(),
                                  user = self.user.get_text(),
                                  private_key_saved = True,
                                  path = self.path.get_text()),
                              automaticBackups = self.automatic_backups.get_active(),
                              configurationType = "local" if self.backup_type.get_model()[self.backup_type.get_active_iter()][0] == 'Local' else "remote")):
            self.close_and_reset()
        else:
            # TODO - handle this in a better way in the UI
            print(error)
        
    def on_cancel_clicked(self, item):
        self.close_and_reset()
        
    def close_and_reset(self):
        self.reset_on_show = True
        self.window.hide()
    
    def on_configuration_delete_event(self, item, item2):
        self.close_and_reset()
        # don't actually delete the window, just hide
        return True
    
    def on_backup_type_changed(self, combo):
        if combo.get_model()[combo.get_active_iter()][0] == 'Local':
            self.remote_box.set_visible(False)
            self.local_box.set_visible(True)
        else:
            self.local_box.set_visible(False)
            self.remote_box.set_visible(True)

class SnapshotListBoxRow(Gtk.ListBoxRow):
    def __init__(self, timestamp, display_text):
        super(Gtk.ListBoxRow, self).__init__()
        self.timestamp = timestamp
        self.display_text = display_text
        self.add(Gtk.Label(display_text))

class File(object):
    def __init__(self, name, dir):
        self.name = name
        self.dir = dir

class SnapshotViewer():

    def __init__(self):
        self.gladefile = "/home/traack/Programming/github/facsimile-linux/facsimile/src/main/glade/facsimile-backup-viewer.glade"  
        self.builder = Gtk.Builder()
        self.builder.add_from_file(self.gladefile)

        self.builder.connect_signals(self)

        self.window = self.builder.get_object("backup-viewer")
        self.snapshot_list_box = self.builder.get_object("snapshot-list-box")
        
        self.setup_file_browser_gui()
    
    def setup_file_browser_gui(self):
        # Cannot set up the ListStore properly in Glade, because of the data structure I want to represent
        # http://stackoverflow.com/a/22847402/474043 shows us how
        self.file_chooser_model = Gtk.ListStore(GObject.TYPE_PYOBJECT)
        
        self.file_chooser_view = self.builder.get_object("file-chooser-view")
        self.file_chooser_view.set_model(self.file_chooser_model)
        
        self.file_chooser_view.append_column(self.make_column_gui("Name", lambda obj: ("(dir) " if obj.dir else "") + obj.name))
    
    def make_column_gui(self, caption, getter):
        rend = Gtk.CellRendererText()
        col = Gtk.TreeViewColumn(caption, rend)
        def _set_cell_text(column, cell, model, it, ignored):
            obj = model.get_value(it, 0)
            cell.set_property('text', getter(obj))
        col.set_cell_data_func(rend, _set_cell_text)
        return col

    def show(self):
        th = threading.Thread(target=self.populate_snapshot_list, args=())
        th.daemon = True
        th.start()
        self.window.present()
        
    def populate_snapshot_list(self):
        GLib.idle_add(self.display_snapshots_gui, sorted(json.loads(subprocess.check_output(["facsimile", "list-snapshots"], universal_newlines = True)).items()))
    
    def display_snapshots_gui(self, snapshots):
        for timestamp, display_text in snapshots:
            self.snapshot_list_box.add(SnapshotListBoxRow(timestamp, display_text))

        self.snapshot_list_box.show_all()
        
        self.current_snapshot = snapshots[-1][0]
        
        self.change_to_backup_directory_gui("/")
       
    def change_to_backup_directory_gui(self, path):
        self.file_chooser_model.clear()
        th = threading.Thread(target=self.load_backup_directory, args=(path,))
        th.daemon = True
        th.start()
    
    def load_backup_directory(self, path):
        GLib.idle_add(self.update_backup_directory_file_list_gui, path, json.loads(subprocess.check_output(["facsimile", "list-snapshot-files", self.current_snapshot, path], universal_newlines = True)))
    
    def update_backup_directory_file_list_gui(self, path, files):
        self.file_chooser_model.clear()
        for file in files:
            self.file_chooser_model.append([File(file['name'], file['isDirectory'] == True)])
        self.current_path = path
    
    def on_snapshot_list_box_row_activated_gui(self, widget, row):
        self.current_snapshot = row.timestamp
        self.change_to_backup_directory_gui("/")
    
    def on_file_chooser_view_row_activated_gui(self, treeview, path, column):
        model = treeview.get_model()
        iter = model.get_iter(path)
        new_path = os.path.join(self.current_path, model.get_value(iter, 0).name)
        self.change_to_backup_directory_gui(new_path)
        
    def on_back_button_clicked_gui(self, extra):
        new_path = os.path.dirname(self.current_path)
        self.change_to_backup_directory_gui(new_path)
        
    def on_restore_button_clicked_gui(self, extra):
        print("restore")

class App():
    def __init__(self):
        self.configuration_dialog = ConfigurationDialog(self.save_configuration)
        self.indicator = AppIndicator3.Indicator.new("facsimile-toolbar",os.path.abspath('/usr/share/facsimile-toolbar/images/backup1.svg'), AppIndicator3.IndicatorCategory.SYSTEM_SERVICES)
        self.indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)
        

        menu = Gtk.Menu()
        
        self.menu_item = Gtk.MenuItem("Loading...")
        menu.append(self.menu_item)
        self.show_snapshots = Gtk.MenuItem("View Backed up files...")
        menu.append(self.show_snapshots)
        self.show_snapshots.show()
        self.show_snapshots.connect('activate', self.open_show_snapshots_window)
        self.config_item = Gtk.MenuItem("Edit Configuration...")
        menu.append(self.config_item)
        self.menu_item.show()
        self.config_item.show()
        self.config_item.connect('activate', self.open_configuration_window)
        
        self.indicator.set_menu(menu)

        th = threading.Thread(target=self.update_status_menu_item, args=())
        th.daemon = True
        th.start()
        
        th2 = threading.Thread(target=self.verify_icon_rotation, args=())
        th2.daemon = True
        th2.start()

        GLib.MainLoop().run()
        
    def save_configuration(self, configuration):
        with subprocess.Popen(["pkexec", "--user", "facsimile", "facsimile", "set-configuration"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True) as proc:
            (stdout_data, stderr_data) = proc.communicate(json.dumps(configuration))
            return None if proc.returncode == 0 else "%s %s" % (stdout_data, stderr_data)
    
    def open_configuration_window(self, item):
        if self.backupRunning:
            return
        th = threading.Thread(target=self.get_config_then_open_window, args=())
        th.daemon = True
        th.start()
        
    def get_config_then_open_window(self):
        GLib.idle_add(self.configuration_dialog.show, json.loads(subprocess.check_output(["facsimile", "get-configuration"], universal_newlines = True)))

    def open_show_snapshots_window(self, item):
        SnapshotViewer().show()
        
    def lastBackupTime(self):
        try:
            snapshots = json.loads(os.popen("facsimile list-snapshots").read())
            return snapshots[max(snapshots)]
        except:
            return "unknown"
    
    def update_status_menu_item(self):
        self.backupRunning = False
        while True:
            try:
                os.chmod('/var/lock/facsimile', stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IWGRP | stat.S_IROTH | stat.S_IWOTH)
            except:
                pass
            with open('/var/lock/facsimile', 'w') as lockfile:
                try:
                    # if facsimile lock file can be locked, a backup is not running
                    fcntl.lockf(lockfile.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
                    fcntl.lockf(lockfile.fileno(), fcntl.LOCK_UN)
                    self.backupRunning = False
                    GLib.idle_add(self.config_item.set_label, "Edit Configuration...")
                except:
                    self.backupRunning = True
                    GLib.idle_add(self.config_item.set_label, "Edit Configuration disabled during backup")
                GLib.idle_add(self.config_item.set_sensitive, not self.backupRunning)
            if self.backupRunning == True:
                try:
                    with open('/var/cache/facsimile/status') as statusfile:
                        message = "Estimated remaining backup time: %s minutes" % json.loads(statusfile.read()).get(u'time_remaining')
                        GLib.idle_add(self.menu_item.set_label, message)
                except:
                    GLib.idle_add(self.menu_item.set_label, "Estimated remaining backup time: unknown")
            else:
                GLib.idle_add(self.menu_item.set_label, "Last backup completed at " + self.lastBackupTime())
                    
            time.sleep(5)
    
    def verify_icon_rotation(self):
        icon = 1
        while True:
            if self.backupRunning == True:
                icon = icon % 16 + 1
                GLib.idle_add(self.indicator.set_icon, "/usr/share/facsimile-toolbar/images/backup%s.svg" % icon)
            elif icon != 1:
                GLib.idle_add(self.indicator.set_icon, '/usr/share/facsimile-toolbar/images/backup1.svg')
                icon = 1
                    
            time.sleep(0.1)

if __name__ == "__main__":
    App()
