#!/bin/bash

set -e

#DEBHELPER#
#!/bin/bash

set -e

# It is possible that Debconf has already been removed, too.
if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }

#
# - Do NOT purge logs or data if another facsimile package is installed
# - Remove the facsimile user only after all its owned files are purged.
#   
if [ "$1" = "purge" -a ! \( -x /usr/bin/facsimile -o -L /usr/bin/facsimile \) ]; then
  # we remove the facsimile user only after all its owned files are purged
  rm -f /var/log/facsimile.log{,.0,.[123456789].gz}

  rm -rf /var/lib/facsimile
  rm -rf /var/cache/facsimile
  rm -rf /var/lock/facsimile
  rm -rf /etc/sudoers.d/facsimile
  rm -rf /var/log/facsimile.log
  userdel facsimile || true
fi

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
fi

#DEBHELPER#

exit 0
